import Head from 'next/head';
import styles from './About.module.scss';
const About = () => {
  return (
    <>
      <Head>
        <title>Easy - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.root}>
        <h1 title='About Route'>About route</h1>
      </section>
    </>
  )
}
export default About;