import { useRouter } from 'next/router';
import styles from './Product.module.scss';
import Head from 'next/head';


const Product = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Easy - {router?.query?.id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.root}>
        <h1 title='Product Id'>This is a route of product Id: {router?.query?.id}</h1>
        <h1 title='Query params'>This is a query params: {router?.query?.sku}</h1>
      </section>
    </>
  )
}
export default Product;